# Generated by Django 4.2.4 on 2023-10-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_practice', '0003_todoevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoevent',
            old_name='user_id',
            new_name='user',
        ),
    ]
